### ISSUE TITLE
percentage sign in message

### ISSUE THREAD

**Issue by daroczig** [zatonovo/futile.logger#26]
I was logging some messages including a percentage sign, which was working fine until the most recent (`1.4`) release. E.g. demo with `futile.logger_1.3.7`:

```r
> flog.debug('%m')
DEBUG [2015-04-15 20:49:02] %m
```

But now with `futile.logger_1.4`:

```r
> flog.debug('%m')
Error in (function (fmt, ...)  : unrecognised format specification '%m'
> flog.debug("%a")
Error in (function (fmt, ...)  : too few arguments
```

**Comment by muxspace** [comment]
I'm doubtful that it has something to do with the change in version of futile.logger, although it's possible that there was a separate function clause when no args were passed. Under the hood, it still uses `sprintf` to manage the formatting, so it's surprising that this worked without issue before. Probably the best thing to do is `flog.debug('%%m')`, which escapes it properly within `sprintf`.

**Comment by daroczig** [comment]
@muxspace if I revert to `1.3.7` on the same computer (no other packages updated/downgraded), then there is no need to escape the percentage sign.

**Comment by muxspace** [comment]
I stand corrected. It looks like `layout.simple` was changed to accommodate NULL values. An artifact is that the message is always passed to `sprintf` instead of short cutting if there are no further arguments. I actually think this is better behavior since otherwise there is different behavior depending on whether additional parameters are passed to the function. This way if a format argument is forgotten, the code will barf appropriately:
```R
> flog.info("%s")
Error in (function (fmt, ...)  : too few arguments
```

**Comment by daroczig** [comment]
I'd argue with that :) I think the error message is not very helpful and the user has to do a `traceback` to find out why he cannot log a simple string -- independently what characters lurk inside. If you indeed want to make this as the default behavior from now (passing to `sprintf` even if not needed), then please
1. update the docs so that the users can realize that they have to pre-process the string as this breaks functionality of downstream packages, and
2. return a helpful error message.

But once again, I do not agree with this solution. E.g. I like to build my log messages with `paste` and some `pander` calls before passing to `futile.logger`, and I can imagine some other guys as well not using the `sprintf` features.

If the old behavior is not something you would like to bring back (omitting an argument changes functionality), then can we please have a new argument like `fixed` in `sub`, so that I can log simple dumb messages without pre-processing? Although I still love the old behaviour: not passing to `sprintf` if there's no sense in doing that.

**Comment by muxspace** [comment]
The only strings that break are ones that have a character sequence that looks like a format. Nothing else is affected. e.g. `flog.info("Hello, I am a no argument format string")` works just fine.

It's unfortunate that there was a regression in the functionality between 3.7 and 3.8, but since I don't get paid for writing and maintaining this package, I don't have the resources to make it as robust as it could be. You are welcome to add tests and submit a pull request.

Also keep in mind that there are multiple layouts available in the package. If you don't like the default or the others provided, you are welcome to create your own that meets your needs exactly.

**Comment by daroczig** [comment]
You are right, using a custom layout is a much cleaner solution to check if `sprintf` is indeed needed. Do you accept a pull request to update the default layout or you are happy with the current behavior and I should use my own in the downstream projects?

**Comment by muxspace** [comment]
Funny enough I just got bit by this as well. I didn't realize that even something like `flog.info("Value is greater than 10%")` will fail. So if you want to be a good sport, how about merging the two behaviors and adding a unit test to prevent further regressions?

**Comment by daroczig** [comment]
Happy to do that, I already have it on my localhost -- will push after I added some tests, but before that, can you please let me know what is the expected output at https://github.com/zatonovo/futile.logger/blob/master/tests/testthat/test_layout.R#L23? I am a bit confused by the following checks. The resulting string is intended to include `NULL` or not?

**Comment by muxspace** [comment]
It looks like these tests are not implemented properly. I'm fixing them now and pushing an update. Thanks for pointing it out!

**Comment by muxspace** [comment]
Okay try now. When you submit, I'll verify locally, tag, and submit to CRAN.
