### ISSUE TITLE
Write to Multiple Logs

### ISSUE THREAD

**Issue by sbryfcz** [zatonovo/futile.logger#30]
I have a need to write to multiple log files which correspond to different threshold levels. We have log files that get progressively more detailed. So we have a log file for TRACE and higher, a log file for INFO and higher, and a log file for ERROR and higher. 

I could build loggers for each of these like:
```R
flog.logger(name='trace',threshold=TRACE, appender=appender.file('trace.txt'))
flog.logger(name='info',threshold=INFO, appender=appender.file('info.txt'))
flog.logger(name='error',threshold=ERROR, appender=appender.file('error.txt'))
```

but then I have to litter my code with a bunch of statements like:
```R
flog.info('test', name = 'trace')
flog.info('test', name = 'info')
flog.info('test', name = 'error')
```

Ideally, I'd write one flog.info method and it logs to all of my appenders.

Maybe I'm doing it wrong. Can multiple appenders by added to a log based on thresholds? It looks like log4j supports that functionality but I cant figure it out with this package. Or is there another approach to take? Any help would be great.

**Comment by muxspace** [comment]
Hi, that behavior isn't really supported in the package. Initially I didn't add it because I felt like log4j got too complicated by trying to support so many use cases. I had planned on adding support for multiple appenders a while back, and adding a threshold to an appender could be added to that work. It wouldn't be too hard to add this, although right now it's not on my list of priorities. 

Have you considered writing to a single file and then using grep to extract the messages you want? That might be simpler in the short term.

**Comment by sbryfcz** [comment]
Alright. Thanks for the feedback. I'll likely just add some helper functions to my R project and use those to help with the functionality I need. Glad I wasn't missing something.

Thanks for the great project.

**Comment by muxspace** [comment]
Glad you like the library, and sorry I couldn't be of more help.

**Comment by jonathancallahan** [comment]
I agree with sbryfcz that this feature is very desirable. I would like to see logging similar to python's fantastic logging module and wrote a recent blog post describing one way to hack this into futile.logger:

https://www.r-bloggers.com/python-style-logging-in-r/

I'd love to see a more integrated approach to this inside futile.logger.

**Comment by iwccsbfb** [comment]
`
flog.logger(name='trace',threshold=TRACE, appender=appender.file('trace.txt'))
flog.logger(name='info',threshold=INFO, appender=appender.file('info.txt'))
flog.logger(name='error',threshold=ERROR, appender=appender.file('error.txt'))
`
BTW, it is not a good practice to name loggers as `trace`, `info`, or `error`. Because we cannot get the thresholds for these loggers now. Below is the snippet of the `logger.threshold` function. We can see `flog.threshold('info') ` will not match to the correct `lambda.r` function

`
flog.threshold('TRACE', name='ROOT') %as% flog.threshold(TRACE, name)
flog.threshold('trace', name='ROOT') %as% flog.threshold(TRACE, name)
flog.threshold('DEBUG', name='ROOT') %as% flog.threshold(DEBUG, name)
flog.threshold('debug', name='ROOT') %as% flog.threshold(DEBUG, name)
flog.threshold('INFO', name='ROOT') %as% flog.threshold(INFO, name)
flog.threshold('info', name='ROOT') %as% flog.threshold(INFO, name)
flog.threshold('WARN', name='ROOT') %as% flog.threshold(WARN, name)
flog.threshold('warn', name='ROOT') %as% flog.threshold(WARN, name)
flog.threshold('ERROR', name='ROOT') %as% flog.threshold(ERROR, name)
flog.threshold('error', name='ROOT') %as% flog.threshold(ERROR, name)
flog.threshold('FATAL', name='ROOT') %as% flog.threshold(FATAL, name)
flog.threshold('fatal', name='ROOT') %as% flog.threshold(FATAL, name)

    
flog.threshold(threshold, name) %::% numeric : character : .
flog.threshold(threshold, name='ROOT') %as%
{
  flog.logger(name, threshold=threshold)
  invisible()
}

# Get the threshold
flog.threshold(name) %::% character : character
flog.threshold(name='ROOT') %as%
{
  logger <- flog.logger(name)
  names(logger$threshold)
}
`

**Comment by iwccsbfb** [comment]
@sbryfcz @jonathancallahan This feature is done in PR #46 . Feel free to checkout and thank you for the suggestion.
